// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVCidmSKZwdQHXpuaGJvrj3-0zdcJBWqs',
    appId: '1:340368431497:web:ec28e1aaac5c1d61986958',
    messagingSenderId: '340368431497',
    projectId: 'smart-campus-companion-3be60',
    authDomain: 'smart-campus-companion-3be60.firebaseapp.com',
    storageBucket: 'smart-campus-companion-3be60.firebasestorage.app',
    measurementId: 'G-FHN2Y3912C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARqoWR4_T7wONFGeZu2D5BJ8RAnMul1WY',
    appId: '1:340368431497:android:2ea2b4f87b9e0b22986958',
    messagingSenderId: '340368431497',
    projectId: 'smart-campus-companion-3be60',
    storageBucket: 'smart-campus-companion-3be60.firebasestorage.app',
  );
}
