include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Avoid empty catch blocks
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    
    # Style rules
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    always_specify_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    camel_case_types: true
    cancel_subscriptions: true
    cascade_invocations: true
    comment_references: true
    constant_identifier_names: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    flutter_style_todos: true
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: false
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    public_member_api_docs: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_final: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    valid_regexps: true
    void_checks: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/lib/generated/**'
    - '**/ios/**'
    - '**/android/**'
    - '**/web/**'
    - '**/test/**'
    - '**/integration_test/**'
    - '**/build/**'

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    argument_type_not_assignable: error
    invalid_assignment: error
    invalid_cast_new_expr: error
    invalid_cast_new_expr_implicit: error
    invalid_null_aware_operator: error
    missing_default_value_for_parameter: error
    no_default_super_parameter: error
    non_constant_identifier_names: warning
    prefer_const_constructors_in_immutables: error
    prefer_const_literals_to_create_immutables: error
    type_annotate_public_apis: warning
