name: smart_campus_companion
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase Core (always update these together)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.9
  google_sign_in: ^6.1.6
  
  # State Management
  provider: ^6.1.1
  
  # UI
  google_fonts: ^6.1.0
  intl: ^0.20.2
  table_calendar: ^3.0.9
  qr_flutter: ^4.1.0  # Using a stable version
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^16.3.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  
  # Utils
  intl_phone_number_input: ^0.7.3  # Using a known stable version
  flutter_dotenv: ^5.1.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  # intl is already included in the main dependencies list

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.8
  mocktail: ^1.0.4
  mockito: ^5.4.4
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

# Android multidex
android:
  enableDexingArtifactTransform: false